apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dcgm-exporter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: dcgm-exporter
    repoURL: 'https://nvidia.github.io/dcgm-exporter/helm-charts'
    targetRevision: '4.*'
    helm:
      values: |
        nodeSelector:
          kubernetes.io/hostname: mlops-labs-worker2
        extraEnv:
          - name: LD_LIBRARY_PATH
            value: /usr/lib/wsl/lib:/usr/lib/wsl/drivers
        extraVolumeMounts:
          - name: wsl-driver
            mountPath: /usr/lib/wsl
          - name: dev-dxg
            mountPath: /dev/dxg
        extraVolumes:
          - name: wsl-driver
            hostPath:
              path: /usr/lib/wsl
          - name: dev-dxg
            hostPath:
              path: /dev/dxg
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true