apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu-inference-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/sgangavarapu4/ml-inference-gitops-pipeline.git'
    targetRevision: HEAD
    path: apps/ml-inference
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true